### PR TITLE
ffac-mt7915e-hotfix: silence stderr from ls command in cron

### PR DESCRIPTION
**Pull request by T0biii**
Use Community repo again.
Updates:

`61ba5ab` ffac-mt7915e-hotfix: silence stderr from ls command in cron (134)
`db60e8f` Add ffbs-debugbathosts
`41c50c8` ffka-gluon-web-usb-wan-hotplug: clarify the use-case
`03b0bba` in hotplug.d/tty we already know it is a TTY device, so we do not need this check anymore
`c966f97` ffda-wireless-rate-limiter: add package
`b7ba830` improve readme, rename lockfile
`61af535` do not change share_location setting
`983ed32` add lock to update-location-gps lua - improve loop handling
`c4bbc97` Add check if TTY_DEVICE actually exists
`db5be52` ffac-update-location-gp: initial package version
`3df6ac2` ffac-mt7915-hotfix: initial package version
`50f13e2` ffda-usb-wan-hotplug: remove old mesh_wan check (127)
`32a07db` ffbs-collect-debug-info: add package
`b0f302d` ffda-ssh-manager: rename separator variable and function
`532ebcf` ffda-node-whisperer: update url to NodeMonitor

### CODE REVIEW

**Comment by grische** [comment]
@T0biii do any of the above changes affect us except the last commit?

**Comment by T0biii** [comment]
`ffbs-collect-debug-info` sounds interessting but the other commits i think we dont use the packages that got changed there

**Comment by grische** [comment]
Can we rename the PR and maybe the commit messages to mention the new commit? I am kind of missing the most important message of  this PR `ffac-mt7915e-hotfix: silence stderr from ls command in cron`.

**Comment by T0biii** [comment]
we can squash the commits on merge to get the commit message you want. And also change the Titel accordingly :)

**Review by maurerle — APPROVED** [review]

**Comment by T0biii** [comment]
squash message could be: `ffac-mt7915e-hotfix: silence stderr from ls command in cron`
waiting CI to pass

**Pull request merged**
