### PR TITLE
Update Gluon for Ubiquiti UniFi 6 Lite

### PR DESCRIPTION
**Pull request by grische**
- Add support for Ubiquiti UniFi 6 Lite:
  https://github.com/freifunk-gluon/gluon/commit/1eeca33c8df1caa40aeb010891f67e81084817d8
- Deprecate redundant the autoupdater patch

### CODE REVIEW

**Review by goligo — CHANGES_REQUESTED** [review]
Looks like the Gluon commit you chose did not run all CI checks. I would rather move to the latest commit, which also includes new changes from OpenWrt (160ad7eea154fc705262c20b352f4f25adafc7bd).

**Comment by GoliathLabs** [comment]
I would also adopt @goligo's changes, but otherwise everything seems fine :)

**Comment by grische** [comment]
Sure, I can do that. I wanted to keep the changes minimal, but I am happy to go all the way to the recent master.

**Review by goligo — APPROVED** [review]
lgtm

**Pull request merged**
