### PR TITLE
Activate next2stable migration package again

### PR DESCRIPTION
**Pull request by goligo**

### CODE REVIEW

**Comment by goligo** [comment]
No CI build necessary - was contained in v2022.10.2 and tested successfully.

**Comment by grische** [comment]
> No CI build necessary - was contained v2022.10.2 and tested successfully.

Let's just run the CI, what is the advantage of not running it?

**Comment by goligo** [comment]
Saving time and resources.

**Comment by goligo** [comment]
Let's do a quick calculation on how much energy we waste with each unnecessary CI-build - we are running builds for two hours on 23 machines. Obviously there is high load while building, so let's assume 200W power usage. This means a full build uses more than 9kWh of energy.

**Review by grische — DISMISSED** [review]
Let's rebase/update this and run the CI to see if it still builds

**Comment by goligo** [comment]
Maybe I didn't state this clear enough, but I will try again: I don't see any need to run CI builds for this change. The package has been built before, there is no reason to believe that the CI build will be anything else than successful.

**Comment by goligo** [comment]
Btw, also a rebase is not necessary, the file affected by this change has not been changed, it will still merge automatically.

**Comment by grische** [comment]
Without a CI run, we do not know if the firmware still builds, we have no artefacts of this PR and hence cannot test if this PR works. 

About the electricity costs:
A CI run does not cost nearly as much as you described above. If needed, we can talk about this in more detail.

About the update/rebase:
I think that also a rebase/update here would be helpful, as the last time the module was built, was on top of another Gluon and even another OpenWRT version. Apart from the kernel changes, several other packages were updated as part of these updates.

**Comment by goligo** [comment]
Can you please just accept my decision that a CI build is unnecessary here, if you miss technical competence to see yourself that this is obviously the case?

**Comment by goligo** [comment]
But let's take a look at the **complete code** of the package which is to be included here:
```
#!/usr/bin/lua

local uci = require("simple-uci").cursor()

local branch = uci:get('autoupdater', 'settings', 'branch')

if "next" == branch then
    uci:set('autoupdater', 'settings', 'branch', 'stable')
end

uci:save('autoupdater')
```

So can you please elaborate in more detail, how these 6 lines of lua code could possibly be affected by the changes in the latest Gluon or OpenWrt version?

**Review by awlx — APPROVED** [review]
Firmware build was [successful](https://github.com/freifunkMUC/site-ffm/actions/runs/3272275273), so I hope we can settle this discussion.

For the next PRs, we should just agree on "let the CI run through" if it's any change except documentation. For most projects this is considered best practise and if it helps people to review stuff (this is a team effort), we should obey to those standards. Most of the time PRs aren't time critical, and we can wait for the CI to complete. And if the PR is time critical for whatever reason, I am sure the team agrees on an early merge.

**Pull request merged**
