### PR TITLE
contrib: add USB For TP-Link TL-WR1043N v5

### PR DESCRIPTION
**Pull request by grische**

### CODE REVIEW

**Review by GoliathLabs — APPROVED** [review]

**Comment by herbetom** [comment]
Is there a reason for this change? The v5 doesn't have a USB Port.

In fact there was #238 earlier this year to remove USB Packages from the v5.

**Comment by grische** [comment]
> Is there a reason for this change? The v5 doesn't have a USB Port.
> 
> In fact there was #238 earlier this year to remove USB Packages from the v5.

Oh, I thought it had one . This was a cherry-pick from the ffac repo. @maurerle do you know why USB was added there?

**Comment by herbetom** [comment]
In the end it doesn't really matter with `image-customization.lua" on the horizon. I was just curious. My guess would be then that ffac just never applied the removal patch.

**Comment by grische** [comment]
Let's revert this then, no benefit of having this: https://github.com/freifunkMUC/site-ffm/pull/351

**Pull request merged**
