### PR TITLE
Bump gluon to v2022.1 in next

### PR DESCRIPTION
**Pull request by grische**
This PR re-applies b88eced9782f5ef3a98ffd6ae2cab3d6d2c62a93 and removes the autoupdater ecdsa patch again as it is already included in the newest gluon release.

It also removes iptables from GLUON_SITE_PACKAGES to fix build errors that are probably related to  https://openwrt.org/releases/22.03/notes-22.03.0-rc1#firewall4_based_on_nftables

### CODE REVIEW

**Comment by grische** [comment]
Some packages have some antfs(???)-related build errors:
```
2022-05-06T18:19:55.5617165Z CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY  -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY  -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include " LDFLAGS="-L/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -znow -zrelro -Wl,--gc-sections " make --jobserver-auth=3,4  -C /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size COPT_FLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY" KERNEL_DIR="/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/" PREFIX=/usr KBUILD_OUTPUT="/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113" BUILTIN_MODULES="standard icmp tcp udp comment set SET limit mac multiport comment LOG TCPMSS REJECT time mark MARK icmp6 REJECT state CT conntrack SNAT DNAT MASQUERADE REDIRECT" ;
2022-05-06T18:19:55.5645679Z make[7]: Entering directory '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7'
2022-05-06T18:19:55.5667225Z make  all-recursive
2022-05-06T18:19:55.5696011Z make[8]: Entering directory '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7'
2022-05-06T18:19:55.5733332Z Making all in libiptc
2022-05-06T18:19:55.5758612Z make[9]: Entering directory '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/libiptc'
2022-05-06T18:19:55.5764029Z /bin/bash ../libtool  --tag=CC   --mode=compile x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I..  -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 -D_REENTRANT 	-DXTABLES_LIBDIR=\"/usr/lib/iptables\" -DXTABLES_INTERNAL -I../include -I../include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include/uapi -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include/uapi -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include  -Wall -Waggregate-return -Wmissing-declarations 	-Wmissing-prototypes -Wredundant-decls -Wshadow -Wstrict-prototypes 	-Wlogical-op 	-Winline -pipe -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY  -MT libip4tc.lo -MD -MP -MF .deps/libip4tc.Tpo -c -o libip4tc.lo libip4tc.c
2022-05-06T18:19:55.6045633Z OpenWrt-libtool: compile:  x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I.. -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DXTABLES_LIBDIR=\"/usr/lib/iptables\" -DXTABLES_INTERNAL -I../include -I../include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include/uapi -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include/uapi -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include -Wall -Waggregate-return -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wshadow -Wstrict-prototypes -Wlogical-op -Winline -pipe -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY -MT libip4tc.lo -MD -MP -MF .deps/libip4tc.Tpo -c libip4tc.c  -fPIC -DPIC -o .libs/libip4tc.o
2022-05-06T18:19:56.0355724Z OpenWrt-libtool: compile:  x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I.. -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DXTABLES_LIBDIR=\"/usr/lib/iptables\" -DXTABLES_INTERNAL -I../include -I../include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include/uapi -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include/uapi -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include -Wall -Waggregate-return -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wshadow -Wstrict-prototypes -Wlogical-op -Winline -pipe -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7=iptables-1.8.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/iptables-1.8.7/include -I/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY -MT libip4tc.lo -MD -MP -MF .deps/libip4tc.Tpo -c libip4tc.c -o libip4tc.o >/dev/null 2>&1
2022-05-06T18:19:56.0588618Z make[7]: Leaving directory '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.113'
2022-05-06T18:19:56.0590355Z make[8]: *** No rule to make target '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529/dir.o', needed by '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529/antfs.o'.  Stop.
2022-05-06T18:19:56.0592092Z make[7]: *** [Makefile:1822: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529] Error 2
2022-05-06T18:19:56.0592723Z make[6]: Leaving directory '/home/runner/work/site-ffm/site-ffm/gluon-build/packages/packages/kernel/antfs'
2022-05-06T18:19:56.0593600Z make[6]: *** [Makefile:47: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529/.built] Error 2
2022-05-06T18:19:56.0594162Z time: package/feeds/packages/antfs/compile#0.64#0.18#0.88
2022-05-06T18:19:56.0601218Z     ERROR: package/feeds/packages/antfs failed to build.
2022-05-06T18:19:56.0609666Z make[5]: *** [package/Makefile:116: package/feeds/packages/antfs/compile] Error 1
```

EDIT:
This is fixed when building x86-64 on ARM64 ... ?!

**Comment by grische** [comment]
Debugging the rockchip-armv8 logs and comparing it to [latest next](https://github.com/freifunkMUC/site-ffm/runs/6319189089?check_suite_focus=true), it seems that the upstream gluon update from OpenWRT 21.02 to OpenWRT 22.03 bumps quite a lot of packages:
* Kernel 5.4.182 to 5.10.113
* GCC 8.4.0 to GCC 11.2.0
* [and many many more](https://openwrt.org/releases/22.03/notes-22.03.0-rc1#core_components_update)

**Comment by GoliathLabs** [comment]
@grische you can try again as there has been some progress

**Comment by grische** [comment]
@GoliathLabs I don't see any changes that would affect our build failure: https://github.com/freifunk-gluon/gluon/commits/master

**Comment by grische** [comment]
There have been some changes that might impact us. I bumped the PR to latest master:
* https://github.com/freifunk-gluon/gluon/commit/971cde1c3bb9279a0ffc6491c500919588c63ef0
* https://github.com/freifunk-gluon/gluon/commit/1fa9c28d4d48bd9badf5f7c4d97f9df81b505381

I also removed all patches, for now, to see if they are causing the issues.

**Comment by grische** [comment]
* I had a long good look at [genpkglist.py from Darmstadt](https://git.darmstadt.ccc.de/ffda/firmware/site/-/commits/4faa435f6ef30f07498ebe30bd24e14c63ddf232/contrib/genpkglist.py) updated and backported some changes to our genpkglist.py. These changes seem to fix ath79 build issues.
* I also restored all patches, except the rockchip-armv8 factory images. These still seem incompatible.
* Last but not least, I bumped to the [gluon release v2022.1](https://github.com/freifunk-gluon/gluon/releases/tag/v2022.1) that updates OpenWRT modules once again
* Cleaned up git history to remove test commits

**Comment by GoliathLabs** [comment]
Skimming through the build logs, the following seems to be the culprit
```
2022-09-06T13:29:34.9365972Z make[8]: *** No rule to make target '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529/dir.o', needed by '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529/antfs.o'.  Stop.
2022-09-06T13:29:34.9367004Z make[7]: Leaving directory '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.136'
2022-09-06T13:29:34.9368832Z make[7]: *** [Makefile:1831: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529] Error 2
2022-09-06T13:29:34.9369486Z make[6]: Leaving directory '/home/runner/work/site-ffm/site-ffm/gluon-build/packages/packages/kernel/antfs'
2022-09-06T13:29:34.9371203Z make[6]: *** [Makefile:47: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/antfs-2020-02-10-b41ba529/.built] Error 2
2022-09-06T13:29:34.9371665Z time: package/feeds/packages/antfs/compile#0.71#0.23#0.98
2022-09-06T13:29:34.9376141Z     ERROR: package/feeds/packages/antfs failed to build.
2022-09-06T13:29:34.9381823Z make[5]: *** [package/Makefile:116: package/feeds/packages/antfs/compile] Error 1
```

**Comment by grische** [comment]
We are now building x86-64 on arm64. That "fixes" the build issues!

All artefacts can be found in the latest run: https://github.com/freifunkMUC/site-ffm/actions/runs/3045006153

**Comment by grische** [comment]
Bumped to latest `next` and added a patch to fix `xxd` issues we saw during builds: https://github.com/freifunkMUC/site-ffm/pull/177/commits/2cdec545931f62e52e531846c835e0bcb643e201

**Comment by grische** [comment]
* Fixed bug in Github Action workflow for the arm64 build 
* Formatted the Github Action workflow
* Bumped community packages to include https://github.com/freifunkMUC/community-packages/pull/32

EDIT:
* moved MTU to wireguard block (required by above PR): https://github.com/freifunkMUC/site-ffm/pull/177/commits/d5c1bd398c3c1ddd0b41109a61a0bae478e2d5fb

**Review by awlx — APPROVED** [review]
We know it builds so let's do it!

**Pull request merged**
