### PR TITLE
domains: add Wertingen domains

### PR DESCRIPTION
**Pull request by grische**
This is a proposal for the new wertingen domains. See #243 

cc @freifunkMUC/salt-stack @istrator2

### CODE REVIEW

**Review by istrator2 — COMMENTED** [review]
Compared to _ffmuc_augsburg.conf_ in `next_node` section there is no  `name` and no `mac` specified. By intention?

**Comment by grische** [comment]
`mac` has been deprecated for a few years and should not be used for new domains. 
`name`, from what I understood, is optional as well and our value seems to be pretty randomly chosen.

**Review by istrator2 — APPROVED** [review]

**Comment by grische** [comment]
I confirmed that the domain does not show up in config mode (until we have ensured it works), but it can be switched manually:

```
root@testnode:~# gluon-switch-domain 'dummy'
Error: invalid mesh domain 'dummy'
root@testnode:~# gluon-switch-domain 'ffwert_city'
client_loop: send disconnect: Connection reset by peer
```

**Comment by grische** [comment]
Rebased and added back `next_node.name` as this seem to have some effect on our side.

**Review by awlx — APPROVED** [review]

**Pull request merged**
