### PR TITLE
update batman-adv-next_2024_07-15

### PR DESCRIPTION
**Pull request by T0biii**
https://chat.ffmuc.net/freifunk/pl/nfuq7zs6midbuysjn6e1fq46gh
https://www.open-mesh.org/projects/batman-adv/wiki/DAT_DHCP_Snooping#DAT-Timeout-Split-Increase

### CODE REVIEW

**Comment by DasSkelett** [comment]
The mt76x8 build reports `2024-09-13T15:11:09.6598885Z [mktplinkfw2] *** error: images are too big`, the mt7620 build seems to suddenly have problems finding files it just created, which might or might not be due to a too large image?

```
2024-09-13T15:10:32.0663725Z cat /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.new >> /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin
2024-09-13T15:10:32.0818167Z rm -rf /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.new
2024-09-13T15:10:32.0863196Z [mktplinkfw2] firmware file "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-us.bin.new" completed
2024-09-13T15:10:32.0874982Z [mktplinkfw2] firmware file "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-eu.bin.new" completed
2024-09-13T15:10:32.0880421Z cat /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-us.bin.new >> /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-us.bin
2024-09-13T15:10:32.0886995Z cat /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-eu.bin.new >> /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-eu.bin
2024-09-13T15:10:32.0916161Z bash: line 1: 8: Bad file descriptor
2024-09-13T15:10:32.0958926Z echo '{  "metadata_version": "1.1", "compat_version": "1.0",   "supported_devices":["tplink,archer-c50-v1","c50"], "version": { "dist": "OpenWrt", "version": "23.05-SNAPSHOT", "revision": "r23899+7-3001d3c5d4", "target": "ramips/mt7620", "board": "tplink_archer-c50-v1" } }' | fwtool -I - /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin
2024-09-13T15:10:32.1002555Z Failed to open firmware file
2024-09-13T15:10:32.1010462Z make[8]: [Makefile:236: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin] Error 1 (ignored)
2024-09-13T15:10:32.1016002Z sha256sum "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin" | cut -d" " -f1 > "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.sha256sum"
2024-09-13T15:10:32.1036141Z rm -rf /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-us.bin.new
2024-09-13T15:10:32.1051369Z rm -rf /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-eu.bin.new
2024-09-13T15:10:32.1054969Z sha256sum: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin: No such file or directory
2024-09-13T15:10:32.1087453Z [ ! -s "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/key-build" -o ! -s "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/key-build.ucert" -o ! -s "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin" ] || { cp "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/key-build.ucert" "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.ucert" ; usign -S -m "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin" -s "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/key-build" -x "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.sig" ; ucert -A -c "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.ucert" -x "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.sig" ; fwtool -S "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin.ucert" "/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin" ; }
2024-09-13T15:10:32.1105080Z cp /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-us.bin /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-us.bin
2024-09-13T15:10:32.1117943Z cp /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin
2024-09-13T15:10:32.1126345Z cp /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-eu.bin /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-factory-eu.bin
2024-09-13T15:10:32.1163477Z cp: cannot stat '/home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin': No such file or directory
2024-09-13T15:10:32.1166924Z make[8]: [Makefile:234: /home/runner/work/site-ffm/site-ffm/gluon-build/openwrt/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-tplink_archer-c50-v1-squashfs-sysupgrade.bin] Error 1 (ignored)
```

One of the changes is [a new dependency](https://github.com/openwrt/routing/compare/master...T-X:gluon-batman-adv-next:batman-adv-next_2024-07-15#diff-5e392d11eaf42fc844de1b6e87ee3d411ecc1a19901706fa7dae9ceb45a5c2ee) on `brmldproxy` which might not fit in the image anymore?

**Comment by grische** [comment]
@T0biii let's try remove some of the non-mandatory packages. We added a lot of them recently and we can just exclude for mt7620 for now.

**Comment by T0biii** [comment]
we added:
- ffac-mt7915-hotfix
- ffbs-collect-debug-info
- ffmuc-custom-banner

which ones should we remove?

**Comment by DasSkelett** [comment]
In the commit I pushed I also undid the dependency on `gluon-mesh-batman-adv-brmldproxy` which then pulls in `brmldproxy`, which I believe has only been added for testing the new batman-adv multicast features.
It shouldn't be a technical dependency, and _if_ it will be kept, it is most definitely going to be moved to the Gluon wrapper package for batman, and not the OpenWRT kernel package itself before upstreaming.

**Comment by T0biii** [comment]
all cis green now, nice

**Review by DasSkelett — APPROVED** [review]
Works find on my nodes so far. I think it's ready to try out in `next`.

**Comment by T0biii** [comment]
i am not sure if we should wait till it is upstream?

**Comment by T-X** [comment]
@DasSkelett I think you should be able to remove the brmldproxy dependency in a simpler way, via a "-gluon-mesh-batman-adv-brmldproxy" in image-customization.lua. Similar to gluon-ebtables-limit-arp:

https://gluon.readthedocs.io/en/latest/package/gluon-ebtables-limit-arp.html

Right, I initially had started this repository to ease testing the IPv6 multicast parts. And wanted it to be as easy as possible for others to configure and test that. (But I would also hope that generally, long term many communities would be fully layer2 + layer3 multicast routing capable and would route addresses with a routeable IPv6 multicast destination, at least embedded-RP addresses, between each other. As multicast only makes some sense when there are a few more users. And that therefore adding brmldproxy by default would make sense).

Thanks to image-customization.lua removing gluon-mesh-batman-adv-brmldproxy should also be doable on a per device basis.

**Comment by T0biii** [comment]
if someone can take a look at the `image-customization.lua` part we can merge it in next

**Comment by T0biii** [comment]
i would prefer to use upstream updates and dont add more patches to our repo

@grische if you say something different i would reopen this.

**Pull request closed without merging**
