### PR TITLE
[Backport legacy] CI: Update to use Github App (#516)

### PR DESCRIPTION
**Pull request by T0biii**

### CODE REVIEW

**Review by grische — APPROVED** [review]

**Comment by T0biii** [comment]
@grische i am out of ideas why this dont work :/ 
i thought with an Bot Account and with workflow permissions it should work but it seems not to

**Comment by grische** [comment]
@T0biii we should debug what has been changed and see what we missed. From what I remember you were able to get the exact same setup working on your fork?

**Comment by grische** [comment]
@T0biii but for consistency between branches, we probably should merge it anyway.

**Comment by T0biii** [comment]
@grische sur,e it seems that it dont break any working thing

**Pull request merged**
